src/app/globals.css
src/components/common/button/Button.tsx

- 공용 컴포넌트 button 구현
- Outlined button 디자인
- Outlined button의 interaction(default, hover, disabled) 적용
- 수정 버튼도 props로 추가
- Solid button 디자인
- Solid button의 interaction(default, active, done) 적용
- 반응형 적용
Closes #8
| 구현 내용 |           Mobile           |            Tablet & Desktop            |  
| :-------: | :-------------------------: | :-------------------------: | 
|    PNG    | <img width="286" alt="image" src="https://github.com/user-attachments/assets/c736f523-f45b-45c4-b840-fc7bd405b6f6" /> | <img width="281" alt="image" src="https://github.com/user-attachments/assets/3b55a001-e9e9-416b-8b37-6905d5d1b5b3" /> | 
- 공통 컴포넌트 Docs https://admitted-turkey-c17.notion.site/Docs-2245da6dc98c80358a4cddc4b1c962e8
- 관련 비고 사항 없음

[#8]feat: 버튼 공용 컴포넌트 구현

---

src/components/common/button/Button.tsx
src/hooks/useLikeToggle.ts
src/types/button.ts

- Like(찜) 기능을 추가해 3가지 variant를 지원하는 공용 버튼 컴포넌트 구현
- 찜 토글 훅 & 타입 정의
- Like(찜) 반응형 디자인 구현(모바일/태블릿 + 데스크탑)
- 찜 토글 훅 구현(향후 백엔드 연동을 위한 구조 설계)
- 타입 정의 정리(button.ts에 모든 버튼 관련 타입 정의)
Closes #14
| 구현 내용 |           Mobile & Tablet           |            Desktop            |  
| :-------: | :-------------------------: | :-------------------------: | 
|    PNG    | <img width="50" alt="image" src="https://github.com/user-attachments/assets/1dd8554c-e0a6-4e7c-8cd1-8986a8cfbbf5" /> <img width="50" alt="image" src="https://github.com/user-attachments/assets/482bee92-c83c-4286-988b-087ff733dc37" /> | <img width="300" alt="image" src="https://github.com/user-attachments/assets/41580010-33dd-4b3d-a287-a17c9a4b1751" /> <img width="300" alt="image" …

[#14] feat: 공용 컴포넌트 찜 버튼 구현

---

src/app/page.tsx
src/components/common/Chips/CircleTextLabel.tsx
src/components/common/Chips/MoveTypeLabel.tsx

- chips 컴포넌트 타입 선언 위치 통일 
- 다중 삼항연산자 제거
-  chip 컴포넌트 코드 리펙토링 
Closes #6 
- 공통 컴포넌트 Docs https://admitted-turkey-c17.notion.site/Docs-2245da6dc98c80358a4cddc4b1c962e8

[#6]refactor :타입 위치 통일 및 4중삼항 제거 피드백반영

---

src/components/common/input/PasswordInput.tsx

- PasswordInput visible 반대 오류 해결.
- 비밀번호 인풋 컴포넌트에서 visible 아이콘이 반대로 되어있어 수정했습니다.
Closes #25  
- 없음.
- 공통 컴포넌트 Docs : https://admitted-turkey-c17.notion.site/Docs-2245da6dc98c80358a4cddc4b1c962e8?source=copy_link

[#25] Feat/commonComponent-input-fix PasswordInput visible 반대 오류 해결.

---

src/app/providers.tsx
src/components/common/modal/ModalContext.tsx
src/types/modal.ts

- 프로젝트 전역에서 사용할 수 있는 공통 모달 컴포넌트를 구현했습니다.
- 모바일에서는 바텀시트, PC/태블릿에서는 센터 모달로 자동 전환되는 반응형 모달입니다.
- ModalProvider, useModal 커스텀 훅을 통한 전역 모달 관리 구조 설계
- ModalOptions에 type(center/bottomSheet) 옵션 추가 및 반응형 분기 로직 구현
- 버튼, 제목, 내용 등 다양한 커스텀 옵션 지원
- ESC 키, 바깥 영역 클릭 시 닫기 등 접근성 기능 반영
- 팀원용 사용법 DOCS 별도 작성
Closes #38
- 추후 디자인/애니메이션 등 추가 커스터마이징 가능
- 팀원들이 쉽게 사용할 수 있도록 사용법 문서화 완료
- 공통적인 스타일만 틀로 잡은 모달입니다

[#38]feat:공용 컴포넌트 모달 제작

---

src/components/common/card/MovingTypeCard.tsx

- 견적 요청에 사용되는 이사 유형 카드 컴포넌트 제작
- 이사 유형 카드 컴포넌트 반복적인 디자인 컴포넌트로 제작
Closes #65
> ![스크린샷 2025-07-09 181431](https://github.com/user-attachments/assets/0bb6893a-cb19-4d53-9c36-6a01a99ce99e)
-

[#65]feat:이사 유형 카드 컴포넌트 제작

---

src/components/common/card/AddressCard.tsx

- 주소 카드 컴포넌트 seleted 사용으로 UI 구현
- onClick 과 seleted 선택
- 선택된 seleted로 UI 구현
Closes #69
> ![스크린샷 2025-07-09 185554](https://github.com/user-attachments/assets/3d8929d2-666b-43fb-814b-20487f64a8f4)
- 
- onClick은 클릭만 구현이 되기 때문에 seleted로 선택함

[#69]fix: 주소 카드 seleted 사용으로 선택된 UI 구현

---

src/app/notification/page.tsx
src/app/providers.tsx
src/components/common/dropdown/UserActionDropdown.tsx
src/components/common/gnb/GnbActions.tsx
src/components/notification/NotificationList.tsx
src/lib/api/notification.api.ts
src/providers/NotificationSSEProvider.tsx
src/stores/notificationStore.ts
src/types/notification.types.ts

SSE 로 실시간 알림을 구현.
헤더바 내의 알림 아이콘을 클릭시 아이콘 아래에 모달로 알림 리스트가 무한스크롤로 나열되고.
해당 알림을 누르면 읽음 처리가 되며 해당 페이지로 이동.
- SSE 연결을 위한 프로바이더 구현.
- 알림을 전역관리 하기 위해 zustand로 notificationStore 구현.
- gnb 내에 알림 종모양 바로 밑에 드롭다운 형태로 알림을 보여주기 위해 드롭다운 공용 컴포넌트 사용.
- 리스트를 무한스크롤로 알림창 내에서 구현하기 위해 intersection observer 라이브러리 사용.
- 리스트 가져오기와 읽음 처리 API 구현.
- 테스트를 위해 알림 페이지를 임시로 작성하여 버튼 클릭시 테스트용 알림 생성되게 구현.
- 유저가 테스트용 버튼을 누르면 모든 기사님들에게 새로운 견적이 등록됐다고 알림이 가도록 구현하여 SSE 확인. 
- 반응형 구현.
Closes #95 - 알림 구현.
#92 - 분석.
- 현재는 견적이 등록되면 모든 기사님에게 알림이 가지만 리팩토링을 거쳐 해당되는 기사님에게만 가도록 수정 예정.

[#95] Feat/notification 알림 기능 구현.

---

package-lock.json
src/components/common/input/PasswordInput.tsx
src/pageComponents/moverMyPage/edit/EditPage.tsx

- 기본정보수정 리팩토링 및 passwordinput 수정
-  기사님 기본 정보 수정 리팩토링
- 이름,이메일,전화번호 input에 로그인한 유저의 정보 자동으로 채워짐
- Passwordinput 컴포넌트 수정 -> type="button" 추가
- 이메일input -> 글씨 색상 변경
- 눈모양 아이콘 위치 변경
Closes #73 
- 추후에 글로벌 css에 있는 내용으로 리팩토링 예정

[#73] refactor: 기본정보수정 리팩토링 및 passwordinput 수정

---

src/lib/actions/auth.actions.ts
src/lib/api/auth.api.ts
src/lib/api/fetcher.api.ts
src/lib/api/user.api.ts

- JWT 슬라이딩 세션 방식을 적용한 **토큰 재발급 로직**을 구현하였습니다.
- `fetcher.api.ts` 라는 wrapper를 통해 모든 API 요청을 감싸고, 토큰 만료 상황에서 재발급 → 재시도 흐름을 자동화하였습니다.
Closes #135
- 엑세스 토큰 유효 기간: **30분**
- 리프레쉬 토큰 유효 기간: **2주**
- 리프레쉬 토큰 재발급 조건: **남은 유효기간 5일 이하**

[#135] feat : 토큰 재발급 로직 적용 및 재발급 사용을 위한 래핑 함수 구현

---

src/app/[locale]/(auth)/callback/page.tsx
src/lib/api/auth.api.ts
src/middleware.ts
src/pageComponents/auth/callback/AuthCallback.tsx
src/pageComponents/auth/moverSignin/MoverSigninPage.tsx
src/pageComponents/auth/moverSignup/MoverSignupPage.tsx
src/pageComponents/auth/userSignin/UserSigninPage.tsx
src/pageComponents/auth/userSignup/UserSignupPage.tsx
src/providers/AuthProvider.tsx

- 구글/카카오/네이버 소셜 로그인 구현
- 로그인 콜백 전용 페이지 구현
- 구글 리디렉션 로그인 구현
- 카카오 리디렉션 로그인 구현
- 네이버 리디렉션 로그인 구현
Closes #58 
- 현재 네이버는 요청 url을 한 개만 설정 가능해서 배포 주소만 설정해둔 상태입니다.

[#58] feat : 구글/카카오/네이버 소셜 로그인 구현

---

src/components/common/dropdown/UserActionDropdown.tsx
src/components/common/gnb/GnbActions.tsx
src/components/notification/NotificationList.tsx
src/providers/NotificationSSEProvider.tsx
src/stores/notificationStore.ts
src/types/notification.types.ts

- 여러 원인으로 인한 실시간 알림 기능 문제 해결.
- 스키마 대공사로 인한 타입 변경.
- 알림 읽음 처리 후 변하지 않는 UI 문제 해결.
- 새로운 알림이 생성 되었을때 실시간으로 바뀌지 않는 문제 해결.
Closes #172 - 스키마 대공사 리팩토링.
Closes #197 - 알림 읽음 처리 후 UI 문제 해결.
Closes #199 - SSE 실시간 알림 기능 문제 해결.
> https://github.com/user-attachments/assets/059fad03-168a-42cf-9db7-5bb1656f32b5
- 테스트용 알림 생성 API 및 notification 페이지는 삭제 예정입니다.
- 현재는 테스트도 겸할 생각으로 새로운 견적요청이 생성되면 모든 기사님에게 알림이 갑니다. 
- 추후 리팩토링 과정에서 서비스 가능 지역에 해당하는 기사님에게만 가도록 변경 예정입니다. - 챌린지 사항.

[#172] [#197] [#199] Feat/notification 실시간 알림 기능 문제 해결.

---

src/messages/en.json
src/messages/ko.json
src/messages/zh.json
src/pageComponents/moverMyPage/MoverMyPage.tsx
src/pageComponents/moverMyPage/edit/EditPage.tsx
src/pageComponents/profile/edit/MoverEditPage.tsx

- 기사님 기본정보 수정 페이지, 기사님 마이페이지, 기사님 프로필 수정 페이지에 다국어 기능을 구현했습니다.
기사님 기본정보 수정 페이지 다국어 구현
- useTranslations("edit") 훅 사용
- 제목, 라벨, 플레이스홀더, 버튼 텍스트, 에러/성공 메시지 번역 키 적용
기사님 마이페이지 다국어 구현
- useTranslations("mover") 훅 사용
- 로딩 메시지, 버튼 텍스트, 섹션 제목 번역 키 적용
기사님 프로필 수정 페이지 다국어 구현
- useTranslations("profile") 및 useTranslations("mover") 훅 사용
- 폼 라벨, 플레이스홀더, 검증 메시지, 모달 메시지 번역 키 적용
---
- ko.json, en.json, zh.json에 새로운 번역 키 추가
Closes #217 
- getServiceTypeTranslation() 및 getRegionTranslation() 유틸리티 함수를 활용하여 일관된 번역 처리
- 반응형 디자인 개선으로 다국어 환경에서도 안정적인 UI 제공

Feat:기사님 페이지 다국어 기능 완성 및 UI 개선

---

src/components/common/dropdown/UserActionDropdown.tsx
src/components/common/gnb/GnbActions.tsx

- GNB 및 유저 드롭다운 다국어 작업.
- GNB 다국어 코드 수정.
- 유저 드롭다운 다국어 코드 수정.
Closes #224 - GNB 및 유저 드롭다운 다국어 작업.

[#224] Feat/gnb GNB 및 유저 드롭다운 다국어 작업.

---

src/messages/en.json
src/messages/ko.json
src/messages/zh.json
src/pageComponents/moverMyPage/edit/EditPage.tsx

- 기사님 기본정보 수정 페이지에서 alert 대신 모달을 사용하도록 변경
- 모달에 다국어 기능 추가
- EditPage.tsx 컴포넌트에 useModal 훅 추가
- alert() 호출을 open() 모달 호출로 변경
- 다국어 파일(ko.json, en.json, zh.json)에 모달 관련 키 추가
Closes #72 

feat:기본정보 수정 모달 구현

---

package-lock.json
package.json
src/app/layout.tsx
src/components/common/gnb/Gnb.tsx
src/components/common/gnb/GnbActions.tsx
src/components/common/gnb/ProfileModal.tsx
src/components/common/gnb/RoleToggle.tsx
src/components/common/gnb/SideGnb.tsx
src/hooks/useSwitchUserType.tsx
src/lib/api/auth.api.ts
src/messages/en.json
src/messages/ko.json
src/messages/zh.json
src/middleware.ts
src/pageComponents/profile/edit/CustomerEditPage.tsx
src/providers/AuthProvider.tsx

- 사이드바에가 현재 pathName과 일치할시 텍스트가 강조되지않던 오류 수정
- 간편 로그인 전환 구현
- 간편 로그인 전환 토글 컴포넌트 구현
- 사이드바 컴포넌트 수정
Closes #191 
Closes #247
https://github.com/user-attachments/assets/ac35f658-0cd6-423b-b82a-8e5b349d1ba9
https://github.com/user-attachments/assets/723d3e48-5d94-4f63-a852-9ae9031cf1da
- 유저 플로우 테스트 필요
- 현재 양쪽 역할(CUSTOMER, MOVER) 모두 프로필을 등록한 경우에만 간편 전환이 가능하도록 제한했습니다.
이는 SSR 환경에서 미들웨어가 토큰 갱신 이전 상태로 동작하면서,
프로필이 등록된 계정으로 이동 시 잠깐 /profile/register 페이지가 노출되는 문제가 발생했기 때문입니다.
UX 혼란을 방지하기 위해 해당 조건으로 제한했습니다.

[#247] feat : 간편 로그인 전환 기능 구현 및 사이드바 오류 수정

---

src/app/[locale]/layout.tsx
src/app/globals.css
src/hooks/useEstimateRequestApi.tsx
src/hooks/useSwitchUserType.tsx
src/pageComponents/favoriteMover/FavoriteMoverPage.tsx
src/utils/shareUtils.ts
src/utils/toastUtils.ts

- 전역상태로 구현되어 있던 토스트 라이브러리를 활용하여 프로젝트에 맞는 디자인으로 수정
- 토스트 라이브러리 디자인 임포트
- 디자인 수정
- 토스트 알림을 사용하는 모든 페이지 변경

fix:토스트 라이브러리를 사용하여 토스트 디자인 변경

---

src/components/common/gnb/GnbActions.tsx
src/components/notification/NotificationList.tsx
src/lib/api/notification.api.ts
src/messages/en.json
src/messages/ko.json
src/messages/zh.json
src/providers/NotificationSSEProvider.tsx
src/stores/notificationStore.ts

- 데이터 리패칭 문제 해결 및 FE 다국어 처리.
- SSE가 재연결을 리랜더링 될때마다 진행해 발생한 알림 데이터를 무한 리패칭하는 문제를 유저id가 바뀔때만 재연결하여 해결.  
- deepL을 BE에서 처리하기 때문에 FE에선 쿼리파라미터로 언어만 넘겨주어 다국어 처리.
Closes #301 - 다국어 작업.
Closes #302 - 데이터 리패칭 지옥.

[#301] [#302] [알림] 데이터 리패칭 문제 해결 및 FE 다국어 처리.

---

src/components/common/gnb/GnbActions.tsx
src/components/notification/NotificationList.tsx
src/lib/api/notification.api.ts
src/stores/notificationStore.ts

- 일반 유저와 기사님 알림 따로 처리.
- 일반 유저와 기사님에 모두 해당하는 유저는 각각의 알림을 따로 받도록 유저 타입 추가.
- 쿼리 파라미터로 유저타입 전달.
Closes #309

[#309] [알림] 일반 유저와 기사님 알림 따로 처리.

---

src/app/globals.css
src/components/estimateRequest/common/EstimateRequestFlow.tsx
src/components/estimateRequest/common/EstimateRequestLayout.tsx
src/components/estimateRequest/create/AddressSearchDaum.tsx
src/components/estimateRequest/create/SpeechBubble.tsx
src/hooks/useEstimateRequestApi.tsx
src/hooks/useEstimateRequestForm.tsx
src/pageComponents/estimateRequest/create/EstimateRequestCreatePage.tsx
src/pageComponents/estimateRequest/edit/EstimateRequestEditPage.tsx
src/types/estimateRequest.ts

- 견적 요청 피드백 반영
- 토스트 알림 색상 변경
- 견적 요청 느리게 올라오는 애니메이션 제거
- 견적 요청 로컬스토리지 저장 제거
- 견적 요청 api 캐싱 고려하여 페이지 접근 시 get 요청 한 번만 보내게
- 견적 요청 카카오 API iframe으로 적용하여 팝업 차단 유저 고려
- 토스트 알림 색상 성공 색상인 초록색으로 변경
Closes #234
- 라이트 하우스 고려 전

[#234]repactor:견적요청 피드백 반영 및 토스트 알림 색상 변경

---

src/components/common/button/Favorite.tsx
src/components/searchMover/MoverCard.tsx
src/hooks/useMoverData.ts
src/pageComponents/favoriteMover/FavoriteMoverPage.tsx

- 찜한 기사님 페이지에 옵티미스틱 업데이트 반영
- 옵티미스틱 업데이트 반영
- 스크린 리더 고려하여 태그 사용
- 시맨틱 태그로 변경
https://github.com/user-attachments/assets/a783d92d-5f79-4a94-ada7-c72f1cc90181
- 지연님이 피드백 주셨던 무한 스크롤 시 전체 조회가 안되고 삭제 시 그제서야 남은 기사님이 조회되는 문제는 해결하지 못했습니다

fix:피드백 반영하여 옵티미스틱 반영, 필요시 다음 페이지 자동로드, 시맨틱 태그 사용, 스크린 리더 고려

---

src/app/[locale]/layout.tsx
src/app/[locale]/providers.tsx
src/components/auth/signin/SigninForm.tsx
src/components/auth/signup/SignupForm.tsx
src/lib/api/fetcher.api.ts
src/lib/api/user.api.ts
src/lib/server/getServerUser.ts
src/middleware.ts
src/pageComponents/profile/edit/CustomerEditPage.tsx
src/pageComponents/profile/register/CustomerRegisterPage.tsx
src/pageComponents/profile/register/MoverRegisterPage.tsx
src/providers/AuthProvider.tsx

- 기존 CSR 중심(AuthProvider 내부 `useState`/`useEffect`/경로 기반 호출/주기적 `setInterval`)의 유저 관리 로직을 SSR + React Query 기반으로 전환
- 초기 진입 시 SSR에서 유저를 프리패치하여 하이드레이션하고, CSR에서는 이벤트 기반 수동 갱신으로 단순화
- SSR (초기값 시드)
- `app/[locale]/layout.tsx`: `QueryClient.prefetchQuery(['user'], getServerUser)` + `dehydrate`로 하이드레이션 상태 전달
- `lib/server/getServerUser.ts`: 최초 접속 시 유저 데이터만 안전하게 조회(401/비정상 응답 시 예외 대신 `null` 반환)
- React Query / AuthProvider
- `providers/AuthProvider.tsx`:
- `useQuery(['user'])`를 단일 소스로 통합하고 자동/주기 호출 제거(`enabled: false`, `refetchInterval: false`)
- 필요 시 명시적으로 `getUser()` 호출(프로필 등록/수정, 역할 전환 등)
- 토큰 슬라이딩 세션: 고정 주기(14분) 선제 갱신 + 포커스/visibility 복귀 시 즉시 갱신
- refresh는 single-flight로 중복 방지
- API/인증 보강
- `lib/api/fetcher.api.ts`:
- Authorization 헤더 조건부 부착(빈 토큰으로 `Bearer null` 전송 방지)
- 401 발생 시 …

refactor : 유저관리 로직 수정

---

src/middleware.ts

- 미들웨어에서 정적 파일 요청 우회 로직 및 matcher 수정  
- 로컬 환경에서 public 폴더 정적 이미지가 차단되는 문제 해결
- `STATIC_PREFIXES` 배열로 정적 파일 경로 정의 (`/img`, `/images`, `/fonts`, `/icons` 등)
- `isStatic` 조건 추가해 정적 파일 요청 시 `NextResponse.next()`로 조기 반환
- `matcher`를 수정해 확장자 있는 모든 파일(`.*\..*`)과 `_next`, `_vercel` 경로 제외
- `.next` 디렉토리 삭제 후 dev 서버 재시작 시 반영 확인

fix : 미들웨어에서 정적파일은 우회되도록 수정

---

src/app/[locale]/review/layout.tsx
src/components/common/LanguageInitializer.tsx
src/hooks/useEstimateRequestForm.tsx
src/i18n/request.ts
src/middleware.ts
src/pageComponents/profile/edit/CustomerEditPage.tsx
src/pageComponents/profile/register/CustomerRegisterPage.tsx

✨ 작업 개요
다국어 구조 변경
✅ 주요 작업 내용
`src/i18n/request.ts`: 모듈 상단의 `en.json`, `ko.json`, `zh.json` 일괄 import 제거
- 요청된 로케일만 동적 import로 로드: `const messages = (await import(...)).default`
- 효과: 서버 번들/파싱 및 직렬화 비용 감소, 초기 로드/TTFB 개선
`src/components/common/LanguageInitializer.tsx`
- 클라이언트 측 자동 리다이렉트 제거
- 최초 진입 시 선호 언어 저장만 수행, 로케일 변경 시 설정 동기화만 유지
- 효과: SSR 이후 클라 더블 네비게이션/깜빡임 제거
`src/middleware.ts`
- 경로 매칭 단순화: "/"와 "/:path*"만 매치 후 내부에서 직접 분기
- 정적/파일 요청은 즉시 우회 유지
- 비로케일 경로는 서버에서 선호 로케일로 SSR 리다이렉트(/{preferredLocale}${pathname})
- 로케일 경로(예: /{locale}/...)에서만 보호/인증 분기 수행
- 효과: i18n-only 이동에서 엣지 미들웨어/토큰 처리 오버헤드 최소화, 404 오매칭 문제 해소
`src/pageComponents/profile/register/CustomerRegisterPage.tsx`, `src/pageComponents/profile/edit/CustomerEditPage.tsx`
- use-intl → next-intl로 임포트 통일
- 효과: 컨텍스트/번들 혼용 제거
🔄 관련 이슈
📸 …

fix:다국어 구조 변경
