- src/app/globals.css
- src/app/page.tsx
- src/components/common/Chips/CircleTextLabel.tsx
- src/components/common/Chips/MoveTypeLabel.tsx
- src/hooks/useMediaQuery.ts
- Chip 공용컴포넌트 제작
- ~ 이사유형 라벨 chip 컴포넌트 개발
- ~ 동그란 텍스트 라벨 chip 컴포넌트 개발
Closes #6 
> 
> [#6]feat:chip 공용컴포넌트 개발

- src/app/(auth)/moverSignup/page.tsx
- src/app/(auth)/userSignup/page.tsx
- src/pages/auth/moverSignin/MoverSigninPage.tsx
- src/pages/auth/moverSignup/MoverSignupPage.tsx
- src/pages/auth/userSignin/UserSigninPage.tsx
- src/pages/auth/userSignup/UserSignupPage.tsx
- src/pages/auth/userSignup/page.tsx
- src/types/auth.ts
- 회원가입 UI 구현
Closes #21 
- pages 폴더의 signup 파일 2개만 확인해주시면 됩니다
> [#21] feat : 일반, 기사님 회원가입 UI 구현

- src/components/quote/create/ChooseAddressBtn.tsx
- 견적 요청에서 사용되는 주소 선택 버튼을 컴포넌트로 제작함
- 공통적인 스타일은 공통 컴포넌트로 제작하고 안에 들어갈 text는 props로 받도록 제작
Closes #79
>
-
-
> [#79] feat: 주소 선택 버튼 컴포넌트 제작

- src/components/quote/create/ProgressBar.tsx
- 어떤 컴포넌트를 어떻게 구현했는지 간단한 개요 작성
- 진행바 컴포넌트 구현
Closes #80
- 
- 진행바를 처음 구현해봐서 이렇게 구현해도 실제 동작에서 문제가 없을지 모르겠습니다 여러 테스트를 해본 후 PR 올립니다
> [#80]feat:진행바 제작

- src/components/quote/create/Calendar.tsx
- 견적 요청에 사용되는 달력 구현
-  `date-fns`를 사용하여 달력 구현
Closes #89 #81
>
- 이슈에서 알 수 있듯이 외부 라이브러리는 디자인이 자유롭지 못하다는 단점이 있어서 직접 제작하게 되었습니다
> [#89]feat: 견적요청에 사용되는 달력 api 구현

- src/app/quote/create/page.tsx
- src/components/common/modal/ModalContext.tsx
- src/components/quote/QuotePageWrapper.tsx
- src/components/quote/create/SpeechBubble.tsx
- src/components/quote/create/card/AddressSearchDaum.tsx
- src/messages/en.json
- src/messages/ko.json
- src/messages/zh.json
- src/pages/quote/create/QuoteCreatePage.tsx
- src/pages/quote/edit/QuoteEditPage.tsx
- src/services/quoteService.ts
- src/types/modal.ts
- src/types/quote.ts
-  챌린지로 두었던 견적 요청 수정 삭제 페이지 제작
- wrapper를 만들어서 분기처리
- 세션에 데이터를 저장하여 patch로 수정할 수 있게 제작
- 프론트와 백 연결
Closes #111
> [before / after 비교가 있으면 같이 첨부해주세요](https://github.com/user-attachments/assets/f8b408b1-a388-4323-82c3-2c08618f96ed)
- 챌린지에 두었던 작업이라 디자인 없어서 오래걸렸습니다
- 디자인은 이전에 사용했던 말풍선 디자인 그대로 사용했습니다
- window를 사용할 수 밖에 없는 이유는 route.refresh()를 사용할 경우 부모 컴포넌트가 ssr 이여야 가능합니다
> [#111]feat:견적요청 수정 삭제 페이지 제작

- src/providers/AuthProvider.tsx
- getUser 비회원 오류
- getUser에서 비회원일때 에러 발생
- 에러 대신 null 반환
Closes #122
> [#122] fix: getUser 비회원 오류 해결

- src/app/globals.css
- src/components/common/dropdown/UserActionDropdown.tsx
- 프로필 및 알림에서 사용되는 드롭다운 제작
- 프로필과 알림의 공통 디자인을 묶고
- 나머지 디자인 중에서 헤더 부분만 제작 후 나머지는 다 프롭스로 받도록 제작
> <img width="477" height="403" alt="스크린샷 2025-07-16 185539" src="https://github.com/user-attachments/assets/5ec482f0-bbad-4539-9edf-a9af2710ffaf" />
- 급하게 만들어서 수정사항이 있을 수 있습니다 언제든지 말해주세요
> feat:프로필 및 알림 드롭다운 제작

- src/lib/actions/auth.actions.ts
- src/lib/api/auth.api.ts
- src/lib/api/user.api.ts
- src/pages/auth/moverSignin/MoverSigninPage.tsx
- src/pages/auth/moverSignup/MoverSignupPage.tsx
- src/pages/auth/userSignin/UserSigninPage.tsx
- src/pages/auth/userSignup/UserSignupPage.tsx
- src/providers/AuthProvider.tsx
- src/utils/auth.ts
- src/utils/validators.ts
- 코드 오류 사항 수정 및 코드 개선
- 토큰 -> 쿠키 저장 로직 개선 및 조회 로직 개선
- 로그인/회원가입 유효성 검사가 백엔드와 맞지 않던 문제 해결 후 유효성 검사에 걸릴시 모달창을 보여주도록 수정
Closes #131
> [#131] 코드 오류 사항 수정 및 코드 개선

- next.config.ts
- src/components/searchMover/[id]/Chip.tsx
- src/components/searchMover/[id]/DetailInformation.tsx
- src/components/searchMover/[id]/MoverIntro.tsx
- src/components/searchMover/[id]/RequestButton.tsx
- src/components/searchMover/[id]/ReviewAvg.tsx
- src/components/searchMover/[id]/ReviewList.tsx
- src/components/searchMover/[id]/TopBar.tsx
- src/lib/api/findMover.api.ts
- src/lib/utils/mockReviewData.ts
- src/pages/searchMover/[id]/SearchMoverDetailPage.tsx
- src/types/findMover.ts
- src/types/moverDetail.ts
- 기사님 상세 컴포넌트 및 api 연결
- 기사님 상세 페이지에 해당하는 모든 컴포넌트 제작 완료
Closes #142 
Closes #143
- 지정 견적 요청, 찜하기, sns 공유 기능은 아직 미완성 (중간 발표 이후에 진행 예정)
- 리뷰만 mock data 연결
> [#142] feat: 기사님 상세 컴포넌트 및 api 연결

- src/lib/api/user.api.ts
- 프로필 등록 api 호출이 로컬 url로 호출하던 문제 수정
-프로필 등록 api 호출이 로컬 url로 호출하던 문제 수정
> fix : 프로필 등록 api 호출이 로컬 url로 호출하던 문제 수정

- src/app/profile/register/page.tsx
- src/components/common/DevNavitgation.tsx
- src/components/common/gnb/Gnb.tsx
- src/components/common/gnb/GnbActions.tsx
- src/constant/profile.ts
- src/lib/api/auth.api.ts
- src/lib/api/user.api.ts
- src/middleware.ts
- src/pageComponents/auth/moverSignup/MoverSignupPage.tsx
- src/pageComponents/auth/userSignin/UserSigninPage.tsx
- src/pageComponents/auth/userSignup/UserSignupPage.tsx
- src/pageComponents/profile/register/CustomerRegisterPage.tsx
- src/pageComponents/profile/register/MoverRegisterPage.tsx
- src/providers/AuthProvider.tsx
- src/types/auth.ts
- src/types/user.types.ts
- src/utils/decodeAccessToken.ts
- src/utils/validators.ts
- 로그인/회원가입 리팩터링
- 로그인/회원가입 리팩터링
Closes #140 
- 프로필 등록 에러 문제 수정 예정
> [#160] refactor : 로그인/회원가입 리팩터링

- src/components/common/chips/MoveTypeLabel.tsx
- src/components/common/gnb/LogoAndTab.tsx
- src/components/estimate/LabelArea.tsx
- src/components/estimateRequest/(my)/CardList.tsx
- src/middleware.ts
- src/pageComponents/estimate/received/MoverReceivedPage.tsx
- src/pageComponents/profile/edit/CustomerEditPage.tsx
- src/utils/locale.ts
- i18n 적용에 맞춰 미들웨어 설정 수정
- 각 언어에 맞게 미들웨어가 동작하도록 수정
- 혹시 추가적인 버그가 발생하면 바로 말씀해주세요
> fix : i18n 적용에 맞춰 미들웨어 설정 수정

- src/components/review/writable/ReviewWriteModal.tsx
- src/components/review/writable/StarRating.tsx
- src/components/review/writable/WritableMoverCard.tsx
- src/components/review/written/WrittenMoverCard.tsx
- src/lib/api/review.api.ts
- src/pageComponents/review/writable/WritableReviewPage.tsx
- src/types/review.ts
- 누락된 리뷰 id 추가 및 date 타입 string으로 변경.
Closes #193 - 타입 및 기타 코드 수정.
#93 - 작성 가능한 리뷰 페이지
#94 - 내가 작성한 리뷰 페이지
#172  - 스키마 대공사 리팩토링
#92 - FE 분석
- seed 데이터에 여러 리뷰가 들어가 있어서 편하게 test 진행, 확인했습니다.
> [#193] Refactor/review 타입 및 기타 코드 수정.

- src/pageComponents/auth/moverSignin/MoverSigninPage.tsx
- src/pageComponents/auth/moverSignup/MoverSignupPage.tsx
- src/pageComponents/auth/userSignin/UserSigninPage.tsx
- src/pageComponents/auth/userSignup/UserSignupPage.tsx
- src/pageComponents/profile/register/MoverRegisterPage.tsx
- src/providers/AuthProvider.tsx
auth, profile 버그 수정
- 로그인, 회원가입시 잘못된 반환값으로의 모달 상태 처리로 인한 오류 수정
- 기사님 프로필 등록 페이지에서 잘못된 초기값 설정으로 인한 제공 서비스 선택 오류 수정
> fix : auth, profile 버그 수정

- src/components/searchMover/[id]/ReviewList.tsx
- src/pageComponents/moverMyPage/MoverMyPage.tsx
- 기사님 마이페이지의 리뷰 시스템 및 UI/UX 전면 개선
- ReviewList 컴포넌트에 사용자 이름 마스킹 기능 추가
- 
- ReviewList 컴포넌트: 사용자 이름 마스킹 함수 추가 (첫 글자 + * )
- UI/UX 개선
- 기사님 리뷰 리스트 컴포넌트 적용
Closes #208 
> fix:기사님 마이페이지 리뷰 리스트 적용  및 코드 최적화

- src/pageComponents/profile/register/CustomerRegisterPage.tsx
- src/pageComponents/profile/register/MoverRegisterPage.tsx
기사님 프로필 등록 오류 수정
- 기사님 프로필 등록 오류 수정
> fix : 기사님 프로필 등록 오류 수정

- src/app/globals.css
- 다크 모드에서 테마 설정으로 인해 원하는 색상이 안나오는 문제 해결
- ~ global.css 수정
Closes #218
>
> [#218]fix: 다크 모드에서 css가 잘못 출력되는 문제 해결

- src/components/common/gnb/GnbActions.tsx
- src/components/moverMyPage/schedule/CalendarWithSchedule.tsx
- src/hooks/useMoverScheduleApi.tsx
- src/lib/api/moverScheduleService.ts
- src/messages/en.json
- src/messages/ko.json
- src/messages/zh.json
- src/pageComponents/moverMyPage/schedule/MoverSchedulePage.tsx
- src/types/schedule.ts
- src/utils/scheduleUtils.ts
- 일정 관리 페이지 api 연결
- 일정 관리 페이지 제작
- 일정 관리 페이지 api 연결
- 리액트 쿼리 사용
Closes #227
> [#227]feat: 기사님 일정관리 페이지 api 연결

- src/app/globals.css
- src/components/common/pending/MovingTruckLoader.tsx
- src/components/estimateRequest/EstimateRequestPageWrapper.tsx
- src/components/estimateRequest/common/EstimateRequestFlow.tsx
- src/components/estimateRequest/common/EstimateRequestLayout.tsx
- src/components/estimateRequest/common/EstimateRequestStepRenderer.tsx
- src/components/estimateRequest/create/ProgressBar.tsx
- src/components/estimateRequest/create/SpeechBubble.tsx
- src/hooks/useEstimateRequestApi.tsx
- src/pageComponents/estimateRequest/create/EstimateRequestCreatePage.tsx
- src/pageComponents/estimateRequest/edit/EstimateRequestEditPage.tsx
- 견적요청 중복 코드 삭제 
- 견적 요청에서 많은 중복 코드가 발견되어 통일 시킴
- 코드 가독성 증가
- 리액트 쿼리를 활용한 로딩 시스템 구현
#234
- 이슈는 라이트 하우스까지 한 후 닫을 예정
https://github.com/user-attachments/assets/d0bf8b46-09d5-41a5-86eb-d39891334867
- 직접 테스트
- 로딩 시스템은 노션 참고
> [#234] refactor:견적 요청 중복 코드 삭제 및 로딩 구현

- src/lib/api/fetcher.api.ts
- 토큰 리프레쉬 에러 수정
- 토큰 리프레쉬 에러 수정
> fix : 토큰 리프레쉬 에러 수정

- src/components/common/gnb/RoleToggle.tsx
- src/lib/api/auth.api.ts
- 소셜 로그인 간편 전환 수정
- authApi.ts의 switchUserType에 credentials: "include" 가 빠진거 확인후 추가함
> fix : 소셜 로그인 간편 전환 수정

- src/components/common/gnb/ProfileModal.tsx
- src/components/common/gnb/RoleToggle.tsx
- src/messages/en.json
- src/messages/ko.json
- src/messages/zh.json
- src/pageComponents/profile/register/CustomerRegisterPage.tsx
- src/pageComponents/profile/register/MoverRegisterPage.tsx
- 프로필 모달 호버 애니메이션 추가 및 간편 전환 호버 메시지창 개선
- 소셜 로그인 계정으로 로컬 로그인시 에러 반환 모달 출력
- 프로필 모달 호버 애니메이션 추가 및 간편 전환 호버 메시지창 개선
- 소셜 로그인 계정으로 로컬 로그인시 에러 반환 모달 출력
Closes #247
> [#247] refactor : 프로필 모달 호버 애니메이션 추가 및 간편 전환 호버 메시지창 개선 및 소셜 로그인 계정으로 로컬 로그인시 에러 반환 모달 출력

- src/hooks/useEstimateRequestAddressModal.tsx
- src/hooks/useEstimateRequestApi.tsx
- src/messages/en.json
- src/messages/ko.json
- src/messages/zh.json
- 견적 요청 리팩토링
- 견적 생성 완료 시 페이지 새로고침이 두 번 되었던 문제 해결
- 견적 요청 주소 선택 모달 번역 오류 해결
- 로딩 시스템 관련 코드 삭제
- SSR로 변경 후 로딩 시스템을 어떻게 하는게 좋을까 고민중입니다
SSR은 서버에서 그려서 내려오는데 어디서부터 어디까지 로딩 상태로 정의하는게 좋을까를 생각중입니다
> repactor: 견적 요청 리팩토링

- src/providers/AuthProvider.tsx
> fix : 로그인 오류 수정

- src/lib/api/user.api.ts
- src/providers/AuthProvider.tsx
- src/utils/auth.ts
- src/utils/logDevError.ts
- 배포 상태에따라 내부 에러 메시지 숨기기가 가능한 유틸함수 구현
- 배포 상태에따라 내부 에러 메시지 숨기기가 가능한 유틸함수 구현
#269
> [#269] feat : 배포 상태에따라 내부 에러 메시지 숨기기가 가능한 유틸함수 구현

- src/components/common/button/Favorite.tsx
- src/components/estimate/CardList.tsx
- src/components/estimateRequest/(my)/CardList.tsx
- src/components/estimateRequest/(my)/LgButtonSection.tsx
- src/components/estimateRequest/(my)/MoverInfo.tsx
- src/components/estimateRequest/(my)/received/EstimateListSection.tsx
- src/components/estimateRequest/(my)/received/LastButtonSection.tsx
- src/lib/api/customerEstimateRequest.api.ts
- src/lib/api/estimateRequest.server.ts
- src/pageComponents/estimate/(my)/rejected/[id]/RejectedDetailPage.tsx
- src/pageComponents/estimate/(my)/request/RequsetPage.tsx
- src/pageComponents/estimate/(my)/request/[id]/RequsetDetailPage.tsx
- src/pageComponents/estimate/received/MoverReceivedPage.tsx
- src/pageComponents/estimateRequest/(my)/pending/UserPendingEstimateRequestPage.tsx
- src/pageComponents/estimateRequest/(my)/received/UserReceivedEstimateRequestPage.tsx
- src/pageComponents/estimateRequest/(my)/received/[id]/UserReceivedEstimateRequestDetailPage.tsx
견적- 유저 좋아요 정보 버그에 따른 API 수정 
API 수정에 따른 테스트코드 수정
- 견적- 유저 좋아요 정보 버그에 따른 API 수정 
- API 수정에 따른 테스트코드 수정
- 견적페이지 데이터 리패칭(캐시무효화)
Closes #265
> [#265] 견적페이지- 좋아요 기능 기능개선 

- src/app/[locale]/profile/edit/page.tsx
- src/app/[locale]/profile/register/page.tsx
- src/components/common/gnb/RoleToggle.tsx
- src/messages/en.json
- src/messages/ko.json
- src/messages/zh.json
- src/pageComponents/profile/edit/IndexEditPage.tsx
- src/pageComponents/profile/register/IndexRegisterPage.tsx
- 프로필 등록/수정 seo 적용
- 프로필 등록/수정 seo 적용
Closes #이슈번호
> [#269] feat : 프로필 등록/수정 seo 적용

- src/components/searchMover/[id]/ReviewList.tsx
- src/lib/api/findMover.api.ts
- 기사님 상세 페이지 리뷰 동적 번역 적용
- 리뷰 content 동적 번역 적용
> refactor: 기사님 상세 리뷰 동적 번역 적용

- src/app/[locale]/(auth)/loading.tsx
- src/app/[locale]/profile/loading.tsx
- src/components/auth/signin/SigninForm.tsx
- src/components/auth/signup/SignupForm.tsx
- src/lib/api/auth.api.ts
- src/pageComponents/profile/edit/IndexEditPage.tsx
- src/pageComponents/profile/register/CustomerRegisterPage.tsx
- src/pageComponents/profile/register/IndexRegisterPage.tsx
- src/pageComponents/profile/register/MoverRegisterPage.tsx
- src/providers/AuthProvider.tsx
- src/providers/QueryProvider.tsx
- src/utils/auth.ts
- 다이렉트 오류 및 에러 모달 숨김 적용
- 다이렉트 오류 및 에러 모달 숨김 적용
- 머지후 배포 주소에서 테스트 진행이 필요합니다
> fix : 다이렉트 오류 및 에러 모달 숨김 적용

- src/messages/en.json
- src/messages/ko.json
- src/messages/zh.json
- src/pageComponents/profile/edit/IndexEditPage.tsx
- src/pageComponents/profile/register/IndexRegisterPage.tsx
- refactor : 프로필 수정/등록 로딩 페이지 적용
- refactor : 프로필 수정/등록 로딩 페이지 적용
Closes #269
> [#269] refactor : 프로필 수정/등록 로딩 페이지 적용

- src/app/globals.css
- src/pageComponents/landing/LadingPage.tsx
- 랜딩페이지 ssr로 변경
- 랜딩페이지 ssr로 변경
- 가로스크롤 방지
#238
> refactor: 랜딩페이지 ssr로 변경

- src/lib/api/auth.api.ts
- src/lib/api/fetcher.api.ts
- src/lib/api/user.api.ts
- src/providers/AuthProvider.tsx
- 프로필 등록시 쿠키 최신화가 안되던 문제 수정
- 프로필 등록시 쿠키 최신화가 안되던 문제 수정
> fix : 프로필 등록시 쿠키 최신화가 안되던 문제 수정

- src/components/common/LanguageSwitcher.tsx
- src/components/common/dropdown/CustomDropdown.tsx
- src/components/common/dropdown/SortDropdown.tsx
- src/components/common/gnb/ProfileModal.tsx
- src/components/searchMover/FilterBar.tsx
- src/providers/AuthProvider.tsx
- refactor : 번역 스위치 개선 및 기사님 찾기 hover css 개선
- refactor : 번역 스위치 개선 및 기사님 찾기 hover css 개선
#307
> [#307] refactor : 번역 스위치 개선 및 기사님 찾기 hover css 개선

- src/middleware.ts
- src/providers/AuthProvider.tsx
- src/utils/decodeAccessToken.ts
- 미들웨어 리다이렉트 문제 수정 및 토큰 재발급 로직 강화
- 미들웨어 리다이렉트 문제 수정 및 토큰 재발급 로직 강화
- setTimeout 함수를 사용하여 만료 직전에 주기적인 재발급을 적용하여 안정성을 강화했습니다
> fix : 미들웨어 리다이렉트 문제 수정 및 토큰 재발급 로직 강화

- src/lib/api/customerEstimateRequest.api.ts
- src/lib/api/moverEstimate.api.ts
- API 에 csrf 적용 롤백
- csrf 적용 롤백 으로 인한 기존 코드 복구
Closes #
> Fix : 견적 API _ csrf 적용 롤백

- src/providers/AuthProvider.tsx
- 토큰 재발급 시간 오류 수정
- 토큰 재발급 시간 오류 수정
- 토큰 재발급 시간을 테스트용이 아닌 실제 서비스용으로 변경했습니다
> fix : 토큰 재발급 시간 오류 수정

- src/app/[locale]/(auth)/loading.tsx
- src/messages/en.json
- src/messages/ko.json
- src/messages/zh.json
- src/pageComponents/profile/register/CustomerRegisterPage.tsx
- src/pageComponents/profile/register/MoverRegisterPage.tsx
- src/providers/AuthProvider.tsx
- 프로필 등록시 유저 정보가 최신화 되지않던 문제 수정 및 프로필 등록 완료 번역 문제 수정
- 각 타입의 메인 페이지 이동시 유저 정보를 한번 최신화 하도록 수정
- 프로필 등록 성공 번역 오류 수정
> fix : 프로필 등록시 유저 정보가 최신화 되지않던 문제 수정 및 프로필 등록 완료 번역 문제 수정

- src/components/common/gnb/Logo.tsx
-  유저 타입에 맞게 로고가 리다이렉트 되도록 수정
-  유저 타입에 맞게 로고가 리다이렉트 되도록 수정
> fix : 유저 타입에 맞게 로고가 리다이렉트 되도록 수정

- src/app/globals.css
- src/components/common/gnb/GnbActions.tsx
- src/components/notification/NotificationList.tsx
- src/providers/NotificationSSEProvider.tsx
- src/stores/notificationStore.ts
- src/types/notification.types.ts
- 다국어 기능 구현 및 펄스 효과 추가.
- SSE 연결 후 초기 데이터 정렬을 위한 패치 함수 제거. -> 쓸데없는 알림 api 호출 제거.
- 알림 다국어 기능 구현 과정에서 title -> message로 변경.
- BE에서 전체 알림 메시지를 deepL로 번역하는 로직 -> 정규식을 사용한 커스텀 번역 -> 메시지를 언어별로 저장해 보여주는 방식으로 구현.
- 새로운 알림 발생시 효과적인 UX/UI를 위해 펄스 효과 추가.
Closes #360 - 쓸데없는 알림 api 호출 제거.
Closes #361 - 다국어 기능 구현.
Closes #362 - 펄스 효과 구현.
> [#360] [#361] [#362] [알림] 다국어 기능 구현 및 펄스 효과 추가.

- src/hooks/useMoverData.ts
- fix:좋아요 캐싱 즉시 무효화 반영
- 즉시 무효화되게 좋아요 캐싱 처리
- npm run dev 정상 동작 확인
> fix:좋아요 캐싱 즉시 무효화 반영

- src/app/[locale]/estimateRequest/create/page.tsx
- src/app/[locale]/layout.tsx
- src/components/common/LanguageSwitcher.tsx
- src/components/common/gnb/Logo.tsx
- src/components/common/gnb/LogoAndTab.tsx
- src/components/estimateRequest/common/EstimateRequestFlow.tsx
- src/components/estimateRequest/common/EstimateRequestLayout.tsx
- src/components/estimateRequest/create/ProgressBar.tsx
- src/components/estimateRequest/create/SpeechBubble.tsx
- src/components/moverMyPage/schedule/CalendarWithSchedule.tsx
- src/components/searchMover/MoverCard.tsx
- src/components/searchMover/MoverList.tsx
- src/hooks/useEstimateRequestApi.tsx
- src/messages/en.json
- src/messages/ko.json
- src/messages/zh.json
- src/pageComponents/estimateRequest/edit/EstimateRequestEditPage.tsx
- src/pageComponents/review/written/WrittenReviewPage.tsx
- 다국어 에러 해결
- 견적 요청 캐싱 적용
- 다국어 로케일 매칭 에러 해결
- 견적 요청에서 캐싱 무효화 해결
-
> fix:견적요청 캐싱 적용 및 다국어 에러 해결

- next.config.ts
- src/lib/api/user.api.ts
- src/messages/en.json
- src/messages/ko.json
- src/messages/zh.json
- src/pageComponents/profile/edit/CustomerEditPage.tsx
- src/pageComponents/profile/register/MoverRegisterPage.tsx
- src/utils/handleAuthErrorToast.ts
- 일반유저 pw 변경 관련 모달 오류 수정
- 일반유저 pw 변경 관련 모달 오류 수정
> fix : 일반유저 pw 변경 관련 모달 오류 수정

- src/app/[locale]/estimateRequest/create/page.tsx
- src/app/layout.tsx
- src/components/estimateRequest/common/EstimateRequestFlow.tsx
- src/components/estimateRequest/common/EstimateRequestStepRenderer.tsx
- src/components/estimateRequest/create/sections/MovingTypeSection.tsx
- src/pageComponents/estimateRequest/create/EstimateRequestCreatePage.tsx
- src/pageComponents/estimateRequest/create/EstimateRequestPage.tsx
- src/utils/shareUtils.ts
- 필요없는 번들 최적화
- 레이아웃에 카톡 공유 스크립트가 있어서 모든 페이지에서 해당 스크립트가 사용됨을 확인 -> 해당 파일로 이동
> fix: 필요없는 번들 최적화

- src/hooks/useMoverData.ts
- 기사님 상세 찜 낙관적 업데이트
Closes #이슈번호
> before / after 비교가 있으면 같이 첨부해주세요
> bug: 기사님 상세 찜 낙관적 업데이트

- src/pageComponents/profile/edit/MoverEditPage.tsx
- 하드코딩된 상수들을 제거하고 공통 상수 파일(profile.ts)을 사용하도록 리팩토링했습니다.
- MoverEditPage.tsx에서 하드코딩된 SERVICE_OPTIONS, REGION_OPTIONS, serviceTypeMapping, regionTypeMapping 제거
- @/constant/profile에서 공통 상수들(SERVICE_OPTIONS, REGION_OPTIONS, SERVICE_MAPPING, REGION_MAPPING) import
Closes #이슈번호
> before / after 비교가 있으면 같이 첨부해주세요
> fix:하드코딩 삭제

- src/components/notification/NotificationList.tsx
- src/components/review/writable/WritableMoverCard.tsx
- src/components/review/written/WrittenMoverCard.tsx
- src/providers/AuthProvider.tsx
- src/providers/NotificationSSEProvider.tsx
- src/stores/notificationStore.ts
- 작업 마무리 및 간단한 변경.
- 커서 포인터 추가.
- 알림 리스트.
- 리뷰 작성하기 버튼.
- 내가 쓴 리뷰 리스트.
- SSE 알림 받아온 뒤 리렌더링 추가.
- 리프레시 토큰 1분에서 14분 변경.
- 리프레시 토큰은 민규님 부탁으로 변경했습니다.
> [알림] [리뷰] 코드 마무리 

- src/app/[locale]/searchMover/[id]/page.tsx
- src/lib/api/findMover.api.ts
- 어떤 컴포넌트를 어떻게 구현했는지 간단한 개요 작성
- ~ 컴포넌트 구현
Closes #이슈번호
> before / after 비교가 있으면 같이 첨부해주세요
> fix: 로컬 포트 삭제
